
apiVersion: v1
kind: ConfigMap
metadata:
  name: rhdh-config
data:
  app-config.yaml: |
    app:
      title: Red Hat Developer Hub
      baseUrl: https://backstage-rhdh-devhub.apps.cluster-xpto.dynamic.redhatworkshops.io

    # Enable guest sign-in without user validation. This configuration
    # is unsafe - only use it for testing when Developer Hub is not
    # connected to upstream sources of data!
    auth:
      providers:
        guest:
          dangerouslyAllowOutsideDevelopment: true
    integrations:
      azure:
        - host: dev.azure.com
          credentials:
            - personalAccessToken: ${AZURE_DEVOPS_PAT}
    backend:
      baseUrl: https://backstage-rhdh-devhub.apps.cluster-xpto.dynamic.redhatworkshops.io
      cors:
        origin: https://backstage-rhdh-devhub.apps.cluster-xpto.dynamic.redhatworkshops.io

    kubernetes:
      serviceLocatorMethod:
        type: multiTenant
      clusterLocatorMethods:
        - type: config
          clusters:
            - name: ocp-cluster
              url: https://kubernetes.default.svc
              skipTLSVerify: true
              authProvider: serviceAccount
              serviceAccountToken: "COLE_O_TOKEN_AQUI" # Ou use uma Secret de ambiente

    catalog:
      providers:
        azureDevOps:
          sandrotanaka:
            organization: "sandrotanaka"
            project: "*"
            repository: "*" # Ou '*' para todos
            path: "/catalog-info.yaml"
            schedule:
              frequency: { minutes: 30 }
              timeout: { minutes: 3 }