apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: create-openshift-namespace
  title: Criar Namespace no OpenShift
  description: Provisionamento automático de namespaces
  tags:
    - openshift
    - infra

spec:
  owner: user:default/guest
  type: service

  parameters:
    - title: Configurações do Projeto
      required:
        - namespace
      properties:
        namespace:
          title: Nome do Namespace
          type: string
          pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
          ui:autofocus: true

  steps:
    - id: create-kubernetes-namespace
      name: Criar namespace
      action: kubernetes:create-namespace
      input:
        namespace: ${{ parameters.namespace }}
        clusterRef: ocp-cluster

  output:
    links:
      - title: Acessar Console do OpenShift
        url: https://console-openshift-console.apps.XXX.dynamic.redhatworkshops.io/k8s/cluster/projects/${{ parameters.namespace }}
